/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package utp.misiontic2022.edu.co.reto4.vista;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import utp.misiontic2022.edu.co.reto4.controlador.ControladorRequerimientos;
/**
 *
 * @author user
 */
public class Requerimiento_Gui extends javax.swing.JFrame {

    private ControladorRequerimientos controlador; 
    private RequerimientoUnoTM requerimientoTM ;
    private RequerimientoDosTM requerimientodosTM;
    private RequerimientotresTM requerimientotresTM;
    public Requerimiento_Gui() {
        controlador = new ControladorRequerimientos();
        initComponents();
        cargarRequerimiento_1();
        cargarRequerimiento_2();
        cargarRequerimiento_3();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ptPrincipal = new javax.swing.JTabbedPane();
        pRequ1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequerimiento1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        ButtonSalida = new javax.swing.JButton();
        preque2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblrequerimiento2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        ButtonSalida1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblrequerimiento3 = new javax.swing.JTable();
        ButtonSalida2 = new javax.swing.JButton();
        Menu_Reo_5 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Mi_Exit = new javax.swing.JMenuItem();
        window = new javax.swing.JMenu();
        Mi_reque_uno = new javax.swing.JMenuItem();
        Mi_reque_dos = new javax.swing.JMenuItem();
        reque3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RETO 5");
        setName("RETO 5"); // NOI18N

        ptPrincipal.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        ptPrincipal.setToolTipText("");
        ptPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ptPrincipal.setFont(new java.awt.Font("Castellar", 0, 10)); // NOI18N
        ptPrincipal.setName("REQUERIMIENTO TRES"); // NOI18N

        pRequ1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REQUERIMIENTO UNO");
        pRequ1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        tblRequerimiento1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        tblRequerimiento1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRequerimiento1.setGridColor(new java.awt.Color(102, 153, 255));
        jScrollPane1.setViewportView(tblRequerimiento1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        ButtonSalida.setBackground(new java.awt.Color(204, 204, 255));
        ButtonSalida.setForeground(new java.awt.Color(255, 0, 0));
        ButtonSalida.setText("EXIT");
        ButtonSalida.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 304, Short.MAX_VALUE)
                .addComponent(ButtonSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 77, Short.MAX_VALUE)
                .addComponent(ButtonSalida))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pRequ1.add(jPanel1, java.awt.BorderLayout.CENTER);

        ptPrincipal.addTab("Requerimiento uno", pRequ1);

        preque2.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Impact", 0, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONSULTA REQUERIMINETO DOS");
        preque2.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        tblrequerimiento2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 204)));
        tblrequerimiento2.setForeground(new java.awt.Color(0, 51, 204));
        tblrequerimiento2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblrequerimiento2.setGridColor(new java.awt.Color(0, 102, 255));
        jScrollPane2.setViewportView(tblrequerimiento2);

        preque2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        ButtonSalida1.setBackground(new java.awt.Color(204, 204, 255));
        ButtonSalida1.setForeground(new java.awt.Color(255, 0, 0));
        ButtonSalida1.setText("EXIT");
        ButtonSalida1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonSalida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalida1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonSalida1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 77, Short.MAX_VALUE)
                .addComponent(ButtonSalida1))
        );

        preque2.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        ptPrincipal.addTab("Requerimiento dos", preque2);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CONSULTA REQUERIMIENTO TRES");
        jPanel2.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        tblrequerimiento3.setForeground(new java.awt.Color(255, 153, 0));
        tblrequerimiento3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblrequerimiento3);

        jPanel2.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        ButtonSalida2.setBackground(new java.awt.Color(204, 204, 255));
        ButtonSalida2.setForeground(new java.awt.Color(255, 0, 0));
        ButtonSalida2.setText("EXIT");
        ButtonSalida2.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        ButtonSalida2.setHideActionText(true);
        ButtonSalida2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonSalida2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalida2ActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonSalida2, java.awt.BorderLayout.PAGE_END);

        ptPrincipal.addTab("REQUERIMIENTO TRES", jPanel2);

        getContentPane().add(ptPrincipal, java.awt.BorderLayout.CENTER);

        Menu_Reo_5.setForeground(new java.awt.Color(0, 51, 204));

        File.setText("File");

        Mi_Exit.setText("Exit");
        Mi_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mi_ExitActionPerformed(evt);
            }
        });
        File.add(Mi_Exit);

        Menu_Reo_5.add(File);

        window.setLabel("window");

        Mi_reque_uno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Mi_reque_uno.setText("Reque 1");
        Mi_reque_uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mi_reque_unoActionPerformed(evt);
            }
        });
        window.add(Mi_reque_uno);

        Mi_reque_dos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Mi_reque_dos.setText("Reque 2");
        Mi_reque_dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mi_reque_dosActionPerformed(evt);
            }
        });
        window.add(Mi_reque_dos);

        reque3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        reque3.setText("Reque 3");
        reque3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reque3ActionPerformed(evt);
            }
        });
        window.add(reque3);

        Menu_Reo_5.add(window);

        setJMenuBar(Menu_Reo_5);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void cargarRequerimiento_2(){
        try {
            var Requerimiento = controlador.consultarRequerimiento2();
            requerimientodosTM = new RequerimientoDosTM(Requerimiento);
            tblrequerimiento2.setModel(requerimientodosTM);
            
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), getTitle(),
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cargarRequerimiento_1(){
        try {
            var Requerimiento = controlador.consultarRequerimiento1();
            requerimientoTM = new RequerimientoUnoTM(Requerimiento);
            tblRequerimiento1.setModel(requerimientoTM);
            
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), getTitle(),
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    private void cargarRequerimiento_3(){
        try{
            var Requerimiento = controlador.consultarRequerimiento3();
            requerimientotresTM  = new RequerimientotresTM(Requerimiento);
            tblrequerimiento3.setModel(requerimientotresTM);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), getTitle(),
                    JOptionPane.ERROR_MESSAGE);
        }
    }
 
    
    private void Mi_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mi_ExitActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,"Desea Cerrar  la Aplicacion",
                           getTitle(),JOptionPane.YES_NO_OPTION, 
                          JOptionPane.WARNING_MESSAGE)==JOptionPane.YES_OPTION){
            dispose();
        }
    }//GEN-LAST:event_Mi_ExitActionPerformed

    private void Mi_reque_unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mi_reque_unoActionPerformed
        // TODO add your handling code here:
        ptPrincipal.setSelectedIndex(0);
    }//GEN-LAST:event_Mi_reque_unoActionPerformed

    private void Mi_reque_dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mi_reque_dosActionPerformed
            // TODO add your handling code here:
           // tpPrincipal.SelectedIndex(0);
           ptPrincipal.setSelectedIndex(1);
         
     
    }//GEN-LAST:event_Mi_reque_dosActionPerformed

    private void reque3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reque3ActionPerformed
        ptPrincipal.setSelectedIndex(2);
    }//GEN-LAST:event_reque3ActionPerformed

    private void ButtonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalidaActionPerformed
        // TODO add your handling code here:
         Mi_ExitActionPerformed(evt);
    }//GEN-LAST:event_ButtonSalidaActionPerformed

    private void ButtonSalida2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalida2ActionPerformed
        Mi_ExitActionPerformed(evt);
    }//GEN-LAST:event_ButtonSalida2ActionPerformed

    private void ButtonSalida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalida1ActionPerformed
      Mi_ExitActionPerformed(evt);
    }//GEN-LAST:event_ButtonSalida1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Requerimiento_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Requerimiento_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Requerimiento_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Requerimiento_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Requerimiento_Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSalida;
    private javax.swing.JButton ButtonSalida1;
    private javax.swing.JButton ButtonSalida2;
    private javax.swing.JMenu File;
    private javax.swing.JMenuBar Menu_Reo_5;
    private javax.swing.JMenuItem Mi_Exit;
    private javax.swing.JMenuItem Mi_reque_dos;
    private javax.swing.JMenuItem Mi_reque_uno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pRequ1;
    private javax.swing.JPanel preque2;
    private javax.swing.JTabbedPane ptPrincipal;
    private javax.swing.JMenuItem reque3;
    private javax.swing.JTable tblRequerimiento1;
    private javax.swing.JTable tblrequerimiento2;
    private javax.swing.JTable tblrequerimiento3;
    private javax.swing.JMenu window;
    // End of variables declaration//GEN-END:variables
}
